runtime: nodejs16

env_variables:
  JWT_SECRET: "3jk4b324b23k3j32b"
  DB_HOST: "34.30.210.225"
  DB_USERNAME: "root"
  DB_PASSWORD: "admin123"
  DB_DATABASE: "testproject"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
